### ISSUE TITLE
Stops working on external IP change?

### ISSUE THREAD

**Issue by Rowbotronics** [MakeICT/automation-scripts#4]
The script stopped sending emails after about a week.  Found that the external IP of home router had changed. After restarting the script it resumed proper function. Not sure where the stdout logs are getting dumped when running as a service.

**Comment by domstoppable** [comment]
Systemd routes stdout from services to a journal. You should be able to view it with something like:
`journalctl -u registration-monitor`

**Comment by Rowbotronics** [comment]
That's what I thought, but it doesn't give me any useful logs when I try that.  This is all I get:


> Jul 31 11:08:47 Gigantor systemd[1]: Stopping WildApricot Registration Monitor...
> Jul 31 11:08:47 Gigantor systemd[1]: Stopped WildApricot Registration Monitor.
> Jul 31 11:08:47 Gigantor systemd[1]: Started WildApricot Registration Monitor.

**Comment by Rowbotronics** [comment]
Never figured this one out, but changed the script to only run periodically so this is no longer an issue.
